### ISSUE TITLE
Gravity Forms skip "Pay with iDEAL" button

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-ideal#63]
http://wordpress.org/support/topic/possible-to-skip-the-pay-with-ideal-button-after-gravity-form?replies=3#post-4184919

**Comment by rvdsteege** [comment]
Issue has been resolved for a while:

- `pronamic_payment_redirect_url` filter has been added in https://github.com/pronamic/wp-pronamic-ideal/commit/ae9154b1953982fdd56bc9ec28d0772b0687e31c
- implementation for Gravity Forms in https://github.com/wp-pay-extensions/gravityforms/commit/4b2af96005574ebc2753b31fe03240d5f4c1892d
