### ISSUE TITLE
Use of comma notation in test_amount

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-ideal#93]
`test_amount` in admin only works with `1.00` notation, not with comma separated values such as `1,00`. Comma notation results in error at payment gateway about invalid amount.

Source: https://github.com/pronamic/wp-pronamic-ideal/blob/develop/classes/Pronamic/WP/Pay/Admin.php#L384

**Comment by remcotolsma** [comment]
Just added thousands and decimal separator settings to the Pronamic iDEAL plugin. If the decimal separator is set to an `,` users should be able a value like `1,50`. 

https://github.com/pronamic/wp-pronamic-ideal/commit/0f09afab8ce87b7f6428bd9f8ad1adadc04795dd
