### ISSUE TITLE
Support iThemes Exchange Free Offers Add-on

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-ideal#94]
iDEAL payment button shouldn't be showing if the Free Offers Add-on is active and the product price is 0 (free).

![schermafbeelding 2015-02-04 om 09 15 37](https://cloud.githubusercontent.com/assets/10371164/6037001/71b6448a-ac4e-11e4-93c1-7639ae8b6540.png)

**Comment by remcotolsma** [comment]
Fixed https://github.com/pronamic/wp-pronamic-ideal/commit/b9eb698df88ea730bbf1b9573a4fcd5ab1b233e7
