### ISSUE TITLE
Question: Is there a check on the characters sent to a gateway?

### ISSUE THREAD

**Issue by BjornW** [pronamic/wp-pronamic-ideal#95]
Not sure just yet if this is a pronamic-ideal issue or a payment gateway issue. It seems Buckaroo has issues accepting certain characters. Doe Pronamic-iDeal filter the data sent to a payment gateway?

**Comment by rvdsteege** [comment]
As far as I know, there aren't any known issues in terms of special characters. Do you get any specific error messages? Which characters are you using?

Source code of the Buckaroo gateway in Pronamic iDEAL can be found at https://github.com/wp-pay-gateways/buckaroo

**Comment by BjornW** [comment]
Thanks for the quick reply. Currently investigating this issue with my client and I'm waiting for their response with regards to which characters are causing issues. Same for the exact error message. When I have the answers I will post them here.

**Comment by rvdsteege** [comment]
Ok, awaiting your response.
