### ISSUE TITLE
Cannot view existing Buckaroo payment configuration

### ISSUE THREAD

**Issue by BjornW** [pronamic/wp-pronamic-ideal#99]
I'm using Pronamic iDeal version 4.3.0 on WordPress Mu 4.5.3(recently converted from single install).

When I want to view the existing Buckaroo payment gateway configuration it is not displayed. In the logfiles the following error message can be found (ip address and domain name have been removed): 

`2016/08/17 10:57:10 [error] 23855#0: *28291 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method Pronamic_WP_Pay_Gateways_Buckaroo_Client::get_error() in /var/www/domain.ext/wp-content/plugins/pronamic-ideal/vendor/wp-pay-gateways/buckaroo/src/Gateway.php on line 68" while reading upstream, client: xx.xx.xx.xx, server: domain.ext, request: "GET /wp-admin/post.php?post=24&action=edit HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.domain.ext", referrer: "https://www.domain.ext/wp-admin/edit.php?post_type=pronamic_gateway"
`

I suspect that our configuration structure is not on par with the current data structure used which causes an error and since this method does not exist results in the log message. Our configuration has been setup in 2014 and has not been changed since.

**Comment by rvdsteege** [comment]
Sorry, this is a bug in our Buckaroo gateway. The issue has already been fixed in https://github.com/wp-pay-gateways/buckaroo/commit/c333bb680d687591297777fe8d906cd33065f385 (that's the file `/wp-content/plugins/pronamic-ideal/vendor/wp-pay-gateways/buckaroo/src/Client.php` on your server), which will be included in the next plugin update.

**Comment by BjornW** [comment]
@rvdsteege thanks for the quick response. What's your ETA for the plugin update?

**Comment by rvdsteege** [comment]
> What's your ETA for the plugin update?

Unfortunately, we can't say anything about release dates of future updates. We're working really hard on some other developments for the Pronamic iDEAL plugin, which we want to include too.

**Comment by BjornW** [comment]
Ok, thanks. Can I safely patch the existing file with https://github.com/wp-pay-gateways/buckaroo/commit/c333bb680d687591297777fe8d906cd33065f385 ?

**Comment by rvdsteege** [comment]
Yes.
